FROM jupyter/tensorflow-notebook:36d857bb0121

ARG CODA_NOTEBOOK_APP_AUTH_REALM=${CODA_NOTEBOOK_APP_AUTH_REALM}
ARG CODA_AUTH_SERVICE_URL=${CODA_AUTH_SERVICE_URL}
ARG CODA_HUB_API_URL=${CODA_HUB_API_URL}
ARG CODA_NOTEBOOK_APP_AUTH_CLIENT_ID=${CODA_NOTEBOOK_APP_AUTH_CLIENT_ID}
ARG CODA_NOTEBOOK_APP_AUTH_CLIENT_SECRET=${CODA_NOTEBOOK_APP_AUTH_CLIENT_SECRET}

ENV CODA_AUTH_SERVICE_URL=${CODA_AUTH_SERVICE_URL}
ENV CODA_HUB_API_URL=${CODA_HUB_API_URL}
ENV CODA_NOTEBOOK_APP_AUTH_CLIENT_ID=${CODA_NOTEBOOK_APP_AUTH_CLIENT_ID}
ENV CODA_NOTEBOOK_APP_AUTH_CLIENT_SECRET=${CODA_NOTEBOOK_APP_AUTH_CLIENT_SECRET}
ENV CODA_NOTEBOOK_APP_AUTH_REALM=${CODA_NOTEBOOK_APP_AUTH_REALM}

ENV RESTARTABLE=yes
ENV JUPYTER_ENABLE_LAB=yes

RUN pip install lxml
RUN jupyter notebook --generate-config -y
RUN echo 'c.NotebookApp.token = ""' >> /home/jovyan/.jupyter/jupyter_notebook_config.py
EXPOSE 8888